### ISSUE TITLE
Crash while rendering overlay/ exception while firing event

### ISSUE THREAD

**Issue by thomaluvr8** [VazkiiMods/Zeta#10]
I genuinely have no clue what's going on here... im just tryna play a custom modpack with 1.20 quark but it crashes once it finishes loading.. 
This is what it says in the launcher: 
![IMG_5610](https://github.com/VazkiiMods/Zeta/assets/163559385/4007c6a6-9d81-490a-b029-7f640be6fa23)

[crash-2024-03-15_11.10.17-client.txt](https://github.com/VazkiiMods/Zeta/files/14617378/crash-2024-03-15_11.10.17-client.txt)

**Comment by Vazkii** [comment]
`raysdongles:strawberry_crop` isn't compatible with Simple Harvest, you have to remove it from that config.
