### ISSUE TITLE
[1.19.2] "java.lang.RuntimeException: could not reload shaders"

### ISSUE THREAD

**Issue by B-Wither** [VazkiiMods/Zeta#12]
[crash-2024-03-18_15.16.56-client.txt](https://github.com/VazkiiMods/Zeta/files/14631818/crash-2024-03-18_15.16.56-client.txt)

**Comment by Vazkii** [comment]
Zeta is not available for 1.19

**Comment by B-Wither** [comment]
Oh my god it is issue of CurseForge, Integrated Dungeons and Structures installed Zeta even for 1.19...
