### ISSUE TITLE
Client crash when opening inventory

### ISSUE THREAD

**Issue by Parkanizor** [VazkiiMods/Zeta#18]
I'm getting an immediate client-side crash anytime I open my inventory. I'm not _too_ great at understanding crash reports, but it seems to potentially be related to Zeta. Removing Quark and Zeta from my modpack resolves the problem.

https://gist.github.com/Parkanizor/3def928b0ec4f9e85407dfbea766c248

Minecraft: `1.20.1`
Forge: `47.2.23`
Quark: `4.0-440`
Zeta: `1.0-16`

**Comment by Rein-the-menace** [comment]
I had the same problem but the new quark update fixed it for me
