### ISSUE TITLE
Zeta Failed to load correctly: java.lang.NoClassDefFoundError: net/minecraftforge/event/BuildCreativeModeTabContentsEvent

### ISSUE THREAD

**Issue by ecpeter23** [VazkiiMods/Zeta#19]
[crash-2024-04-16_16.47.00-fml.txt](https://github.com/VazkiiMods/Zeta/files/15002331/crash-2024-04-16_16.47.00-fml.txt)

**Comment by HumanF91R** [comment]
if it got autodownloaded by idas on 1.19.2 delete it. It's only on 1.20.1. I guess they added it as a dependency but accidentally did it for all versions.

**Comment by IThundxr** [comment]
zeta is 1.20.1 only, keep using auto reg lib on 1.19.2
