### ISSUE TITLE
Zeta possibly causing creative menu tabs to disappear

### ISSUE THREAD

**Issue by Crankonator** [VazkiiMods/Zeta#20]
Hii, i tried asking in the discord regarding this issue first, but i got no answer.
So i thought i'd try my luck on the github!
ive been having some issues with seemingly random creative tabs disappearing at seemingly random times, so i checked the log and saw zeta was talking about some creative tab stuff and that i should enable Creative Verbose Logging which i then did, but dont really know what im looking at/for.

the log is too big for me to upload here, on gist and pastebin (both gist and pastebin timed out) as the log is 76mb, so @ me on discord @crankonator

**Comment by Crankonator** [comment]
fixed it

**Comment by dogonotoughen** [comment]
How did you fix it??
