### ISSUE TITLE
Crashes with most recent update

### ISSUE THREAD

**Issue by Hot-M3ss** [VazkiiMods/Zeta#23]
[crash-2024-06-11_10.20.15-client.txt](https://github.com/user-attachments/files/15789526/crash-2024-06-11_10.20.15-client.txt)
The game crashes with the most recent update, however version 1.0-16 still works. Have not tested any other version.

**Comment by Zelioth** [comment]
Ensure you are using the latest release of forge for 1.20.1. I am running multiple server and mod packs on Forge 47.2.32 and Zeta version 1.0.19 works perfect

**Comment by Hot-M3ss** [comment]
I think it was an issue with one of the mods that use zeta.

**Comment by YukiRainee** [comment]
[crash-2024-06-21_23.15.40-client.txt](https://github.com/user-attachments/files/15935559/crash-2024-06-21_23.15.40-client.txt)
Seem to be having the same issue here as this person could be related to quark? or something like modular powersuits? I'll give them both a try on my end

**Comment by IThundxr** [comment]
dreams n desires is crashing
