### ISSUE TITLE
[1.20.1] - Crash during Wold Gen / World Load - Exception in server tick loop

### ISSUE THREAD

**Issue by sugan-reden** [VazkiiMods/Zeta#45]
Hi,

I have been getting a crash since a few days and tries ago. Something seems to be interacting with Zeta on world load.

Here's the log :
https://gist.github.com/sugan-reden/9c6580ea8088b200e1013b0dbdd9cd9c

Keep up the good work and take care <3

**Comment by ProjectHSI** [comment]
https://github.com/VazkiiMods/Zeta/blob/1d68bb4827f7373b060ff3605a8d99a092e2f7eb/src/main/java/org/violetmoon/zetaimplforge/event/ForgeEventsRemapper.java#L123

**Comment by ProjectHSI** [comment]
upon further inspection, create: dreams and desires appears to be causing the problem, due to the stack trace mentioning such.

**Comment by ProjectHSI** [comment]
Further inspection of stack trace reveals this.

1. Zeta crawls all recipes
2. Create: Dreams & Desires throws a null pointer exception.
3. Zeta does not catch this exception, and the exception travels up stream until a crash.

**Comment by ProjectHSI** [comment]
CAN BE CLOSED: Create: Dreams & Desires does have a fix but it hasn't been updated to Modrinth.
If you build from source of that mod, it should be alright.

**Comment by sugan-reden** [comment]
Can confirm.  
Deactivating "Create: Dreams & Desires" lets the world gen go through.

I have not tested a build from source yet, but for now, I think this will be enough. I will probably wait for the update (I am not experienced enough yet).

That said, thank you very much for your help, kind human <3. Keep up the good work, and take care :)

---
Versions tested: 
MC 1.20.1
Forge 47.3.6
**Create-DnDesire-1.20.1-0.1b.Release-Early-Dev.jar**
**Zeta-1.0-24.jar**

**Comment by ProjectHSI** [comment]
> Can confirm. Deactivating "Create: Dreams & Desires" lets the world gen go through.
> 
> I have not tested a build from source yet, but for now, I think this will be enough. I will probably wait for the update (I am not experienced enough yet).
> 
> That said, thank you very much for your help, kind human <3. Keep up the good work, and take care :)
> 
> Versions tested: MC 1.20.1 Forge 47.3.6 **Create-DnDesire-1.20.1-0.1b.Release-Early-Dev.jar** **Zeta-1.0-24.jar**

@sugan-reden (in case github doesn't auto-notify you)

steps for you to build from source:
- download jdk 17 and put it anyway (you don't even have to install it, just download it and put it somewhere)
- open up the terminal/console relevant to your system
- set the environment variable "JAVA_HOME" to wherever you stored the jdk (search it up for your terminal)

whenever i tell you to "run" something, you type what i say into the terminal and press enter. if you mess up, hold control and press c to stop the command.

IF YOU HAVE GIT (run 'git' to find out if you have it):
- run `git clone https://github.com/LopyLuna/Create-Dreams-and-Desires.git` in a directory you would like. Note that git creates a new folder to clone a repo to and places the files there.
- run `git checkout ver-Rewrite` ver is to be replaced with 1.19.2 or 1.20.1. It cannot be both. 1.18.2 does not have a rewrite and is likely to be an old version.
- run `cd Create-Dreams-and-Desires`

if you append a name to the git checkout command, it will name it's folder what you put there instead. if you put a . in place of the name, it will be extracted to the current folder the terminal is in (note that you must have an empty folder for this to work)

IF YOU DON'T HAVE GIT AND DON'T WANT TO INSTALLED IT:
- navigate to https://github.com/LopyLuna/Create-Dreams-and-Desires/tree/1.19.2-Rewrite
- above the files list on this page, click on 1.19.2-Rewrite and select the version you would like to use that has '-Rewrite' appended to it. after clicking, you will be navigated to that page.
- click on the green 'code' button and select "download zip"
- extract the zip somewhere on your system
- navigate to your folder on the terminal (or open the terminal in that folder if your os supports.)

note that with *this* method you will need to redo this process when you wish to update your mod.

if you wish to update your mod and you have git, run `git pull` and skip the above steps on gathering the mod.

after downloading the source code:
- run `./gradlew jar` in the folder. append `gradlew` with .bat if running on windows (cmd or powershell. does not apply for other cmd lines)
- wait until the command finishes
- in `build/libs`, you will find the -all version of the jar file. install this into minecraft instance
- launch the minecraft instance and enjoy

**Comment by sugan-reden** [comment]
Hi again! Sorry for the delay, life and work got in the way.

Can confirm that building from source runs! 

Thank you very much for the detailed instructions and for all the help, kind human <3 :)) 

Keep up the good work! And take care 🌟
